import Head from "next/head";
// import Link from "next/link";
import QRCode from "~/components/qr-code";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main> */}
      <Head>
        <title>Frontend Mentor Challenges</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/" />
      </Head>
      <header className="block h-12 w-screen bg-sky-300"></header>
      <nav className="sticky top-0 z-10 h-20 w-screen bg-slate-300 shadow-md"></nav>
      <main className="grid grid-cols-1 items-center justify-evenly gap-x-4 gap-y-8 bg-slate-100 md:grid-cols-2 lg:grid-cols-4">
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
        <QRCode />
      </main>
      <footer></footer>
    </>
  );
}
