import Head from "next/head";
import Content from "~/components/Content";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor Challenges</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/" />
      </Head>
      <header className="block h-12 w-screen bg-slate-200"></header>
      <nav className="sticky top-0 z-10 h-20 w-screen bg-slate-400 shadow-md"></nav>
      <Content />
      <footer></footer>
    </>
  );
}
